### ISSUE TITLE
[AVM Module Issue]: Resource naming condition incorrect

### ISSUE THREAD

**Issue by captainhook** [Azure/terraform-azurerm-avm-res-insights-component#40]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.2

### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.2

### Description

The condition for Application Insights name is incorrect - https://github.com/Azure/terraform-azurerm-avm-res-insights-component/blob/f740c7e1c43001936ddff54f97a840ae4d477364/variables.tf#L12

The correct condition as per Microsoft documentation is: "1-260	chars, Can't use: %&\?/ or control characters. Can't end with space or period."
source: https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftinsights

However on the Azure portal is says, "The resource name must contain between 1 to 255 characters inclusive. The name only allows alphanumeric characters, periods, underscores, hyphens and parenthesis and cannot end in a period."

**Comment by JFolberth** [comment]
Closing as we resolved by #48
