### ISSUE TITLE
[AVM Module Issue]: application_type should be required

### ISSUE THREAD

**Issue by alefteris** [Azure/terraform-azurerm-avm-res-insights-component#52]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.3

### Description

I think that the "application_type" input should be required (as it is in the [application_insights](https://registry.terraform.io/providers/hashicorp/azurerm/3.116.0/docs/resources/application_insights#argument-reference) resource) and not be optional with the default set to `web` (ASP.NET). I think this is a setting that most people will want to customize for their specific application. The module should not default to a Microsoft technology, if this was the reason.

Currently also the variable description for the "application_type" doesn't match the current optional status: "(**Required**) The type of the application. Possible values are 'web', 'ios', 'java', 'phone', 'MobileCenter', 'other', 'store'.".

**Comment by JFolberth** [comment]
This is ultimately a judgement call by the module owner. The application_type is configured as an overridable variable thus any user can submit a value when calling the module. Additionally there is validation on the variable if it is one of the possible values. Though required by the provider it is effectively defaulted to 'web' to allow for tracking one less input. 

Making this change would lead to a breaking change when the ability to override has been documented as an optional type with a defaulted value.

**Comment by JFolberth** [comment]
Reopening as will update the description though. Did not realize that. Thanks for catching.
