### ISSUE TITLE
azurerm plugin crashes when creating AVM application insights resource with minimum permissions

### ISSUE THREAD

**Issue by maniSbindra** [Azure/terraform-azurerm-avm-res-insights-component#70]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

Current

### Description

The issue is related to the azurerm provider version this AVM module is tied to, which is [3.7.1](https://github.com/Azure/terraform-azurerm-avm-res-insights-component/blob/fd404c1b79154ccf0e3173111ec427708b3281b4/terraform.tf#L7). This issue causes the plugin to crash. This happens when the service principal executing the terraform apply does not have sufficient permission to create all resources needed by this AVM module. In this case instead of reporting the missing permissions the plugin crashes. The solution is to update the azurerm version tied to this AVM resource to 4.2 or higher. 

Please see the following github issue against the azurerm provider which has more details and steps to replicate the issue:  https://github.com/hashicorp/terraform-provider-azurerm/issues/27961

**Comment by maniSbindra** [comment]
@JFolberth when the latest version reflect in the module registry. Currently latest version is still show as 0.1.4. 

Error

```There is no available version of module
"registry.terraform.io/Azure/avm-res-insights-component/azurerm" (main.tf:1)
which matches the given version constraint. The newest available version is
0.1.4. 
```

**Comment by cmaclaughlin** [comment]
@JFolberth - it looks like the tag doesn't match the release. I imagine this is why the latest isn't present in the Terraform registry. 

![Image](https://github.com/user-attachments/assets/7bac428e-3e0c-448a-92f7-c5fd2da076d9)
